# Generated by Django 4.2.6 on 2023-10-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
