# Generated by Django 4.2.6 on 2023-10-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_project_description_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gitrepo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
